export type Formation = 'cuisine' | 'service';

export type TechniqueGroup = {
  category: string;
  items: string[];
};

export const techniqueSources: Record<Formation, string> = {
  cuisine:
    'https://referentiels-professionnels.eduscol.education.fr/BP_ADLC/Annexes_BP_ADLC_231019.pdf',
  service:
    'https://referentiels-professionnels.eduscol.education.fr/BP_ASCR/Annexes_BP_ASCR_231019.pdf',
};

export const techniques: Record<Formation, TechniqueGroup[]> = {
  cuisine: [
    {
      category: 'Préparations préliminaires',
      items: [
        'Habiller un poisson plat',
        'Habiller une volaille effilée',
        'Préparer des abats de boucherie',
        'Préparer un céphalopode',
        'Préparer un crustacé',
        'Ouvrir à cru des coquillages et autres fruits de mer',
        'Préparer un plateau de fruits de mer',
      ],
    },
    {
      category: 'Tailles découpes et désossages',
      items: [
        'Hacher au couteau un tartare',
        'Tourner des artichauts ou des têtes de champignons',
        'Détailler des pièces entières de poisson',
        'Détailler un tronçon une darne ou une tranche',
        'Détailler des pièces entières de viande',
        'Découper des pièces entières de gibier ou de volaille',
        'Désosser à cru une pièce de viande ou de volaille',
        'Manchonner une côte ou un carré',
        'Désosser une cuisse de volaille',
        'Désosser une pièce entière',
        'Découper steaks pavés escalopes noisettes ou tournedos',
        'Détailler des pièces de poisson rond ou plat',
        'Lever des filets de poissons ronds ou plats',
        'Désarêter un poisson plat entier',
      ],
    },
    {
      category: 'Apprêts et montages',
      items: [
        'Décortiquer des crustacés crus ou cuits',
        'Dénerver une pièce de viande de volaille ou un filet de poisson',
        'Farcir une portion ou une pièce entière',
        'Contiser une volaille',
        'Ficeler une pièce',
        'Monter une préparation spécifique',
        'Monter une pièce en croûte',
        'Envelopper de feuille de brick ou de pâte à filo',
        'Luter une cocotte',
        'Piquer larder ou barder',
        'Plier des filets de poisson',
      ],
    },
    {
      category: 'Liaisons et foisonnements',
      items: [
        "Lier à l'amidon à la farine ou à la fécule",
        'Lier aux purées de légumes ou de fruits',
        'Lier aux protéines',
        'Lier aux matières grasses par émulsion',
        'Lier aux additifs épaississants ou gélifiants',
        'Foisonner une crème des blancs ou un bouillon',
        'Réaliser une mousse un espuma ou une écume',
      ],
    },
    {
      category: 'Marinades fonds fumets et gelées',
      items: [
        'Réaliser une marinade crue ou cuite',
        'Réaliser une saumure ou un salage à sec',
        "Confire au sucre à l'alcool ou à la graisse",
        'Réaliser un fond brun lié',
        'Réaliser un fumet de poisson ou de crustacés',
        'Réaliser une glace une marmite ou une gelée',
        'Réaliser un court-bouillon ou une nage',
        'Réaliser un blanc de cuisson',
      ],
    },
    {
      category: 'Sauces jus et coulis',
      items: [
        'Réaliser une sauce émulsionnée chaude et ses dérivés',
        'Réaliser un sabayon ou un beurre monté',
        'Réaliser une sauce brune rouge ou tomate',
        'Réaliser une sauce à base de crustacés',
        'Réaliser une gelée ou un gel irréversible',
        'Réaliser un jus de viande volaille poisson ou légume',
        'Réaliser un coulis ou une crème de légumes',
      ],
    },
    {
      category: 'Préparations sucrées',
      items: [
        'Réaliser un sirop un glaçage ou une gelée décor',
        'Cuire un sucre ou réaliser une confiture',
        'Réaliser un granité ou un sorbet',
        'Réaliser une sauce ou une crème anglaise dérivée',
        'Réaliser une bavaroise une mousse un crémeux ou une ganache',
        'Réaliser une crème fouettée ou une crème Chantilly',
        "Réaliser une crème d'amande ou une frangipane",
        'Réaliser un sabayon ou une pâte à bombe',
      ],
    },
    {
      category: 'Appareils et crèmes',
      items: [
        'Réaliser une farce à gratin mousseline ou à la panade',
        'Réaliser un appareil à pommes de terre ou à féculents',
        'Réaliser un appareil à soufflé salé',
        'Réaliser une mousse salée',
        "Réaliser un appareil sucré lié à l'amidon",
        'Réaliser un appareil à soufflé sucré',
        'Réaliser une mousse froide ou chaude',
        'Réaliser une crème pâtissière dérivée',
      ],
    },
    {
      category: 'Pâtes',
      items: [
        'Réaliser une pâte à tuile à cigarette ou à décor',
        'Réaliser une nougatine ou une croquante',
        'Réaliser une pâte à choux',
        'Réaliser une pâte levée fermentée',
        'Réaliser une pâte levée non fermentée',
        'Réaliser une pâte fraîche ou une raviole',
        'Réaliser une pâte battue ou un biscuit',
        'Réaliser une meringue ou un macaron',
        'Réaliser une pâte à crêpes ou une pâte à frire',
      ],
    },
    {
      category: 'Cuissons',
      items: [
        'Sauter griller ou marquer au grill',
        'Sauter déglacer ou cuire au wok',
        'Rôtir ou cuire en atmosphère sèche',
        "Cuire à l'étouffée sous pression ou sous vide",
        'Pocher ou cuire à court mouillement',
        'Frire avec ou sans enrobage',
        'Glacer gratiner ou cuire à la broche',
        'Braiser à brun ou à blanc',
        'Poêler',
        'Cuire à basse ou juste température',
        'Fumer à chaud ou à froid',
      ],
    },
    {
      category: 'Décorations et finitions',
      items: [
        'Lustrer napper masquer glacer ou laquer',
        'Décorer une pièce entière',
        "Décorer un fond d'assiette ou de plat",
        'Écrire au cornet',
        'Façonner des décors à la cuillère',
        'Réaliser un décor en sucre meringue chocolat ou pâte',
        'Sculpter canneler ou historier',
      ],
    },
  ],
  service: [
    {
      category: 'Avant le service',
      items: [
        'Napper avec du linge de table',
        'Réaliser un pliage particulier',
        'Napper un buffet',
        'Dresser une table à la carte',
        'Dresser un salon un séminaire ou un banquet',
        'Redresser une table pour un nouveau service',
        'Réaliser une décoration cohérente avec un thème ou un budget',
        'Réaliser une décoration de table avec accessoires',
        'Réaliser une décoration éphémère florale ou non',
        'Adapter la mise en place à la thématique',
      ],
    },
    {
      category: 'Service simple',
      items: [
        'Servir au plateau des verrines coupes ou assiettes atypiques',
        'Assurer le suivi du rang',
        'Synchroniser plusieurs tables',
        'Effectuer un service de type banquet',
        'Servir un buffet un cocktail un lunch ou un brunch',
        'Assembler et présenter une restauration minute élaborée',
      ],
    },
    {
      category: 'Boissons',
      items: [
        'Préparer et servir un cocktail short ou long drink',
        'Préparer un cocktail au shaker',
        'Préparer un cocktail au blender',
        'Préparer un punch une sangria ou une boisson en contenant collectif',
        'Préparer et valoriser cafés thés ou chocolats',
        'Préparer et servir cafés ou thés glacés',
        'Carafer un vin',
        'Décanter un vin',
        'Réaliser un service du vin au panier',
        'Servir un vin effervescent',
      ],
    },
    {
      category: 'Atelier et office',
      items: [
        'Assembler une verrine ou une assiette nordique',
        'Découper des poissons fumés',
        'Découper un jambon cru à la griffe',
        'Réaliser une vinaigrette à la carte',
        'Ouvrir des coquillages',
        'Préparer un plateau de fruits de mer',
        'Préparer une assiette ou un plateau de fromages',
        'Préparer une assiette de fruits exotiques',
        'Détailler un ananas piston',
        'Préparer une coupe glacée personnalisée',
      ],
    },
    {
      category: 'Préparation et finition en salle',
      items: [
        "Dresser un buffet de hors-d'œuvre",
        'Préparer et servir une soupe de poissons',
        'Détailler un poisson en Bellevue',
        'Détailler un foie gras en terrine',
        'Servir un plat régional ou international avec ses spécificités',
        'Servir et préparer des pâtes au guéridon',
        'Découper une pièce en croûte de sel',
        "Découper un jambon à l'os au torchon ou braisé",
        'Préparer un poisson rond grillé sauté rôti ou à la plancha',
        'Peler une truite au bleu',
        'Détailler un homard une langouste ou un tourteau',
        'Préparer et flamber des crustacés',
        'Préparer un tartare de poissons crustacés ou Saint-Jacques',
        'Découper un canard ou une volaille en plusieurs portions',
        'Découper un carré de viande',
        'Servir un soufflé chaud',
        "Terminer une sauce à l'aide de spiritueux crème beurre ou aromates",
        'Préparer une assiette à partir de fruits flambés',
        'Préparer ou flamber des crêpes ou une omelette norvégienne',
        'Préparer et découper un dessert de chariot ou de buffet',
        'Préparer un tartare de fruits ou de légumes',
        'Réaliser une finition en salle assaisonner zester râper ou verser',
      ],
    },
  ],
};
